version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - SERVER_PORT=:8080
      - DATABASE_URL=postgres://postgres:password@db:5432/txn_service?sslmode=disable
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/txn-service.log
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - txn-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=txn_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d txn_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - txn-network

volumes:
  postgres_data:

networks:
  txn-network:
    driver: bridge
